### ISSUE TITLE
DFM does not open from (re)-loaded workspace

### ISSUE THREAD

**Issue by xbirgitx** [nbbrd/jdemetra-nowcasting#2] opened 2016-08-05 08:59 UTC
When trying to learn how to use this plugin I followed the steps in Wiki and loaded the same workspace as in the example, the BM2014_JAE. Workspace opens, I can see the titles of the three models listed under Nowcasting/documents/DynamicFactorModel. Doubleclicking on the first two gives no result though, nothing opens on the right hand side panel. No errormessages are displayed either. Third one, by some miracle, does open. Is it just me, or ...  ? Running versions 2.1.0 of both JDemetra and the plugin.

**Comment by maggimats** [comment] 2016-08-05 09:47
Hello,

I would need some further information from your side to help resolving the problem.
Can you give me the content of the **messages.log** file please ?

You can find its location by going into JDemetra+ and clicking on menus **Help > About**.
Go in the location named **User directory** and the in **/var/log**.

Thanks

**Comment by Liedo** [comment] 2016-08-05 09:50
I just checked it and you are right. If you open the folder ".\BM2014_JAE\DfmDoc", you will see that there is only one model instead of three. This example has not correctly uploaded (I will try to fix in on monday). There should also be an excel file with the input data so that you are able to play with the refresh options and reproduce the Example 1.

**Comment by xbirgitx** [comment] 2016-08-05 10:04
Hi Mats,

 

Thank you for a prompt reply. For a moment there I thought there was something wrong with my installation as the Wiki must be correct. 

I shall plough through the rest of the Wiki pages, lets hope there’re no more hiccups.

 

Maybe you can answer another question as well (sent it to demetra@nbb.be as well yesterday, but no reply yet): is the last version of the plugin 2.1.0 or is there something newer out there?

I’m a novice to the github environment and I could not quite figure out what was one supposed to do with the files under the master branch. The only .nbm  files I could find/download and install were for version 2.1.0.

 

With best regards,

  Birgit Strikholm

 

Economics and Research Department

Bank of Estonia

**Comment by maggima** [comment] 2016-08-05 10:09
The most recent pre-release version is the 2.1.0 available to download from the Releases tab.
The master branch contains the source code that can be more recent but then you need to clone it, modify it if needed, compile it, etc...

There are currently some developments but we don't have any release date at the moment.

**Comment by marjaluo** [comment] 2017-01-17 06:37
The BM2014_JA has not been correctly uploaded.

**Comment by Liedo** [comment] 2017-01-17 13:20
Thanks for reporting. The problem is solved now. The xml file was missing.

**Comment by marjaluo** [comment] 2017-01-18 02:04
Thank you .I will try late.

发自我的 iPhone

**Comment by marjaluo** [comment] 2017-01-18 05:17
Nowcasting euro area GDP: Understanding the role of qualitative surveys, by R. Basselier, D. De-Antonio-Liedo and G. Langenus (2016) (download model)
This one can not download.

**Comment by marjaluo** [comment] 2017-01-18 08:47
Nowcasting euro area GDP: Understanding the role of qualitative surveys, by R. Basselier, D. De-Antonio-Liedo and G. Langenus (2016) (download model)
This model can not download.

**Comment by Liedo** [comment] 2017-01-18 10:18
The model workspace by Basselier, De-Antonio-Liedo and Langenus (2016) is available now. Thanks for letting me know of additional links are missing.

**Comment by marjaluo** [comment] 2017-01-18 13:49
Thank you . I will try it now.






At 2017-01-18 18:18:42, "Liedo" <notifications@github.com> wrote:


The model workspace by Basselier, De-Antonio-Liedo and Langenus (2016) is available now. Thanks for letting me know of additional links are missing.

**Closed** 2017-01-18 13:56 UTC
